<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <DebugType>none</DebugType>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>1.0.0</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Authors>xiaobright</Authors>
    <RepositoryUrl>https://github.com/xiaobright/pwsh-utf8-hook</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
